### PR TITLE
Convert Sandrah to Ranger/Cleric and change the usability of her excl…

### PR DESCRIPTION
**Pull request by wuxiangjinxing**
I personally feel Sandrah fits a Ranger/Cleric perfectly.  She is neutral good and she has an animal companion.  Besides, there is no R/C companion in either vanilla game or mods, but F/C is not so rare.  Why not making her a little more unique?

For Jenlig: I guess it might be better to make her a F/T because Githyanki, according to DND 3.5 rules, has a favored Class as fighter.  Besides, Githyankis are tall, gaunt humanoids, so it shall be very hard to hide in shadow and do dirty works.

### CODE REVIEW

**Comment by RoxanneSHS** [comment]
The Sandrah changes should be made into a selectable install option. Keep the current files and move the changes into an extra component (folder). In tp2 add an install option that overwrites the original files with the modified ones.

For Jen'lig, I think no change is required because she already techniically acts like a Fighter/thief - she "learns" the specific hide/stealth options only while staying with the group. There are also some dialogues that explore that topic in game.

**Comment by RoxanneSHS** [comment]
The change you propose cannot be done by simply replacing the cre-file.
Sandrah is a fighter-cleric with the secondary class being a kit "Priestess of Mystra". Those are changes that need to be compiled and created during installation.
You can make these changes in your local game (I assume that is how you did it) but they will not work when transferred by simple copy to another installation because the kit references will not fit.

Can you put the changed files into a zip archive and send them to me? You can also attach the zip of the forum-post.

The idea itself is not bad - but a) it should be an option for the player during installation and b) it needs a bit more work and analysis to be integrated into the mod...dual classes are not easy in EE but possible and a kit added to the second class is pretty special and easy to break...

**Comment by wuxiangjinxing** [comment]
> 

This is a little odd because what I did was changing those files and re-install this mod, and then everything works fine in the game (Sandrah can get here kit correctly).   Here is the zip archive with those files I modified. [https://drive.google.com/file/d/12kK6B8rrejdlb037NPaMLjeh2bu3Ix93/view?usp=sharing](url)

I was trying to modify the tp2 file to make it optional.  But sadly I'm really unfamiliar with the Weidu grammar.  It would be nice if you could integrate it since obviously you are quite adept in this work (I can hardly understand the existing codes in that tp2, to be honest).

**Comment by RoxanneSHS** [comment]
It is not odd that your procedure works because the kit was added to the game in the first installation, so after you made the changes and re-installed, the second time around the weidu installed found that the Mystra kit existed and re-used it. This way your references stayed the same. (This is different if you have a clean installation.)

Anyway I will do some testing and see how I can get it to work. Maybe I also need to adjust some dialogues because there is a lot of reference to her skills and education but I do not remember every detail by heart.

Thank you for the files.

**Comment by RoxanneSHS** [comment]
I have implemented your request in a slightly different manner but hopefully with the same outcome.

- item files have now changed flags...they do not need them anyway because only Sandrah can use them due to opcode 318 restrictions.
- the class change is implemented in the Sandrah tweaks mod that already allows for portrait changes, this way it can be selected independently from the main trilogy.

**Comment by wuxiangjinxing** [comment]
There are some differences between F/C and R/C:
1) Ranger has a racial enemy. (My personal suggestion is demonic, 0x79.  But I guess you might have another idea that fits better in Sandrah's story)
2) Ranger can charm animal. (SPCL311)
3) Ranger can stealth (with a 2/3 R/C I would suggest giving her 21 hide in shadows and 21 stealth)
4) Ranger automatically gets 2 star in two weapon skill (0x72).  I would also suggesting giving her 2 star in both war hammer and shield because a lvl 1 character should have 4 weapon profession points but Sandrah current only has 3.

**Comment by RoxanneSHS** [comment]
I have implemented the 1 + 2 (really forgot about that racial enemy...demonic is fine since she already gains a skill against golems during the game - red wizards would be ideal but is not technically possible. Drow is another option but there are too few until Underdark to make much sense.)

I still need to think about 3 +4 - I rather leave it to the player to set it when she levels up shortly after first meeting.

**Pull request closed without merging**
